# Generated by Django 2.0.7 on 2018-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('category', models.TextField(blank=True, max_length=100, verbose_name='category')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name_plural': 'article',
                'verbose_name': 'article',
            },
        ),
    ]
